name: Ci
on:
  push:
    branches-ignore:
      - main
    
jobs:
  pull-from-other-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull from other branch
        run: git fetch && git pull origin $(ref)

      - name: Push to main
        run: git push origin main
